require "import"
import "android.widget.*"
import "android.view.*"
import "android.text.method.*"

layout={
    LinearLayout,
    layout_width="fill",
    layout_height="fill",
    orientation="vertical",
    {
        HorizontalScrollView,
        FillViewport=true,
        layout_gravity="left",
        layout_width="fill",
        {
            TextView,
            text="",
            id="input",
            textSize=40,
            lines=1,
            Gravity="left",
            layout_width="wrap",
            },
        },
    {
        HorizontalScrollView,
        FillViewport=true,
        layout_gravity="right",
        layout_width="fill",
        {
            TextView,
            text="",
            id="output",
            Gravity="right",
            textSize=40,
            onClick="up",
            lines=1,
            layout_width="wrap",
            },
        },
    {
        LinearLayout,
        layout_width="fill",
        layout_height="fill",
        layout_weight="1.0",
        {
            Button,
            text="(",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text=")",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="←",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="C",
            onClick="clear",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        },
    {
        LinearLayout,
        layout_width="fill",
        layout_height="fill",
        layout_weight="1.0",
        {
            Button,
            text="1",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="2",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="3",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="+",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        },
    {
        LinearLayout,
        layout_width="fill",
        layout_height="fill",
        layout_weight="1.0",
        {
            Button,
            text="4",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="5",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="6",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="-",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        },
    {
        LinearLayout,
        layout_width="fill",
        layout_height="fill",
        layout_weight="1.0",
        {
            Button,
            text="7",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="8",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="9",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="*",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        },
    {
        LinearLayout,
        layout_width="fill",
        layout_height="fill",
        layout_weight="1.0",
        {
            Button,
            text="0",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text=".",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="=",
            onClick="enter",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        {
            Button,
            text="/",
            onClick="click",
            layout_width="fill",
            layout_height="fill",
            layout_weight="1.0",
            },
        },
    }

function click(v)
    local t=v.getText()
    if t=="←" then
        local i=input.getText().toString()
        input.setText(string.sub(i,1,-2))
        else
        input.append(t)
        end
    local s,r=pcall(dostring,"return "..input.getText().toString())
    if s then
        if r then
            output.setText(tostring(r))
            else
            output.setText("")
            end
        end
    end

function clear()
    input.setText("")
    output.setText("")
    end
function up()
    input.setText(output.getText())
    end

function dostring(s)
    return assert(loadstring(s))()
    end


function enter()
    local s,r=pcall(loadstring("return "..input.getText().toString()))
    if s then
        if r then
            output.setText(tostring(r))
            else
            output.setText("")
            end
        else
        output.setText("ERROR")
        end
    end

--activity.setTheme(android.R.style.Theme_Material_NoActionBar)
activity.setTheme(android.R.style.Theme_Holo_NoActionBar)

activity.setContentView(loadlayout(layout))
